name: tortellini
on:
  workflow_dispatch:
    # for manual trigger

jobs:
  tortellini:
    runs-on: ubuntu-latest
    steps:

    - run: curl https://research-software.nl/api/software_cache | jq '.[] | .repositoryURLs.github[]' --raw-output > urls.txt

    - uses: tortellini-tools/action@neater-output
      with:
        repositories: urls.txt
        
    - run: tree -L 3
