name: tortellini
on:
  workflow_dispatch:
    # for manual trigger
  schedule:
    # https://crontab.guru/#0_4_1/7_*_*
    - cron: "0 4 1/7 * *"

jobs:
  tortellini:
    runs-on: ubuntu-latest
    steps:

    - run: |
        curl https://research-software.nl/api/software_cache | jq '.[] | .repositoryURLs.github[]' --raw-output > urls.txt

    - uses: tortellini-tools/action@v3
      with:
        repositories: urls.txt
        
    - run: tree -a -L 3

    - uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'eu-central-1'
        SOURCE_DIR: '.tortellini/out'
