name: tortellini
on:
  workflow_dispatch:
    # for manual trigger

jobs:
  tortellini:
    runs-on: ubuntu-latest
    steps:
      - run: curl https://research-software.nl/api/software_cache | jq '.[] | .repositoryURLs.github[]' > urls.txt

      - uses: tortellini-tools/action@fd7e681cc1d5e02f7246d579bd70f68933338e33
        with:
          repositories: 'urls.txt'

      - run: |
          tree -L 4 ./
